### ISSUE TITLE
Target=_blank not working on Home

### ISSUE THREAD

**Issue by weipah** [kyleshockey/ghost-external-links#2]
Hi @kyleshockey 
first of all thanks for putting this script together!

I realized that though that this only works when I first click on any blog post to open, but not when the Home-site is loaded at first.

Would you have an idea why?

[My site](http://ghost.evilism.com) for reference.

Thanks a lot!

Mark

**Comment by shockey** [comment]
Hey @weipah!

Glad to see this being of use to you. It looks like `ghost-external-links.js` isn't being loaded when at your homepage.

Did you use the automated install script, or did you install the script yourself?

**Comment by weipah** [comment]
Thanks for the response @kyleshockey 
I did the file teweaking manually.

I finally find out that there was a default-wide.hbs file, too.
This might be a specialty by the theme I'm using. After changing this as well it now seems to work correctly.

Thanks again!

**Comment by shockey** [comment]
Awesome! Good to hear it's working well now.
